# Generated by Django 5.1.1 on 2024-09-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=15, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='datanascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(max_length=30, verbose_name='UF'),
        ),
    ]
