# Generated by Django 4.2.4 on 2025-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('BCG', 'BCG'), ('Hepatite B', 'Hepatite B'), ('DTPa', 'DTPa'), ('Influenza', 'Influenza')], max_length=100)),
                ('data', models.DateField()),
                ('comprovante', models.ImageField(upload_to='comprovantes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacina',
        ),
    ]
