# Generated by Django 4.2.4 on 2025-04-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculadoradpp',
            name='data_concepcao',
        ),
        migrations.AlterField(
            model_name='calculadoradpp',
            name='tipo_calculo',
            field=models.CharField(blank=True, choices=[('DUM', 'Data da Última Menstruação'), ('Parto', 'Data Provável do Parto')], max_length=50, null=True),
        ),
    ]
