# Generated by Django 4.2.4 on 2025-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganhopeso',
            name='altura',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ganhopeso',
            name='semana_gestacional',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
