# Generated by Django 4.2.4 on 2025-04-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exameposto',
            name='exames_disponiveis',
        ),
        migrations.AddField(
            model_name='exameposto',
            name='exames_disponiveis',
            field=models.CharField(choices=[('SANGUE', 'Exame de sangue'), ('ULTRASOM', 'Ultrassom'), ('ECG', 'Eletrocardiograma'), ('GLICEMIA', 'Teste de glicemia'), ('URINA', 'Exame de urina')], default='SANGUE', max_length=10),
        ),
    ]
