# Generated by Django 4.2.4 on 2025-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aviso_mostrado',
            field=models.BooleanField(default=False, verbose_name='Aviso mostrado ao usuário'),
        ),
    ]
