# Generated by Django 4.2.4 on 2025-04-16 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_cliente_aviso_mostrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meuapp.comentario'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meuapp.topico'),
        ),
    ]
