# Generated by Django 4.2.4 on 2025-04-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_remove_calculadoradpp_data_concepcao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculadoradpp',
            name='tipo_calculo',
        ),
        migrations.AddField(
            model_name='calculadoradpp',
            name='data_concepcao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
