# Generated by Django 4.2.4 on 2025-04-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_remove_exameposto_exames_disponiveis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(max_length=100)),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.RemoveField(
            model_name='exameposto',
            name='exames_disponiveis',
        ),
        migrations.AddField(
            model_name='agendamentoexame',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.exameposto'),
        ),
    ]
