# Generated by Django 4.2.4 on 2025-04-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_gestante_delete_vacina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gestante',
            new_name='Vacina',
        ),
    ]
