# Generated by Django 4.2.4 on 2025-04-04 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_rename_gestante_vacina'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
