# Generated by Django 4.2.4 on 2025-04-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/', verbose_name='Foto do Cliente'),
        ),
    ]
