# Generated by Django 4.2.4 on 2025-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_remove_calculadoradpp_tipo_calculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculadoradpp',
            name='tipo_calculo',
            field=models.CharField(choices=[('DUM', 'Data da Última Menstruação'), ('Parto', 'Data Provável do Parto')], default='DUM', max_length=50),
        ),
    ]
