# Generated by Django 4.2.4 on 2025-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0004_vacina_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/'),
        ),
    ]
