# Generated by Django 4.2.4 on 2025-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_cliente_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='', verbose_name="pload_to='', blank=True, null=True"),
        ),
    ]
