# Generated by Django 4.2.4 on 2025-04-07 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0006_alter_cliente_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GanhoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_inicial', models.FloatField()),
                ('peso_atual', models.FloatField()),
                ('semanas_gestacao', models.IntegerField()),
                ('resultado', models.CharField(max_length=100)),
                ('grafico', models.ImageField(blank=True, null=True, upload_to='graficos_peso/')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
