# Generated by Django 4.2.4 on 2025-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0007_ganhopeso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ganhopeso',
            old_name='data_registro',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='ganhopeso',
            name='resultado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
