# Generated by Django 4.2.4 on 2025-04-07 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0008_rename_data_registro_ganhopeso_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ganhopeso',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='ganhopeso',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='ganhopeso',
            name='semanas_gestacao',
        ),
        migrations.AddField(
            model_name='ganhopeso',
            name='classificacao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ganhopeso',
            name='imc',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ganhopeso',
            name='grafico',
            field=models.ImageField(blank=True, null=True, upload_to='graficos_gestante/'),
        ),
        migrations.AlterField(
            model_name='ganhopeso',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
